version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  groups:
    development-dependencies:
      dependency-type: "development"
- package-ecosystem: bundler
  directory: "test/smarty"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  groups:
    dependencies:
      patterns: [ "*" ]
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
